name: "🐞 Bug report"
description: Report a malfunction (Manager or Runner)
labels: [bug]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which project is affected?
      options:
        - manager
        - runner
        - not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Component version (e.g. 1.0.0) or commit/tag
      placeholder: "1.0.0"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide reproducible steps (if possible)
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste logs here (please redact secrets)
      render: shell
    validations:
      required: false
