name: "✨ Feature request"
description: Suggest an improvement (Manager or Runner)
labels: [enhancement]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - manager
        - runner
        - both
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see implemented?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative approaches?
    validations:
      required: false
